name: Build and Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and Plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material \
                      mkdocs-minify-plugin \
                      mkdocs-git-revision-date-localized-plugin \
                      mkdocs-awesome-pages-plugin

      - name: Build documentation
        run: mkdocs build

      - name: Deploy to VPS via rsync
        uses: Burnett01/rsync-deployments@v7
        with:
          switches: -avzr --delete
          path: site/
          remote_path: ${{ secrets.REMOTE_TARGET }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}